version: 2.1

orbs:
  slim-ai-test-orb: slimdevops/slim-scanner@0.0.4
parameters:
  image-name:
    description: Image to be scanned.
    type: string
    default: sreejithfocaloid/node-example:latest
  image-connector:
    description: Connector.
    type: string
    default: dockerhub.public #Connector used by slim to get the image eg:dockerhub.public
  cimg-tag:
    description: Which tag to be used for cimg/base.
    type: string
    default: current #Which tag to be used for cimg eg:  cimg/base:current
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: << pipeline.parameters.image-name >>
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: cimg/base:<< pipeline.parameters.cimg-tag >>
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
jobs:
  publishLatestToHub: 
    executor: docker-publisher
 
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t << pipeline.parameters.image-name >> .
            docker push << pipeline.parameters.image-name >>

workflows:
  engine-execution:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - publishLatestToHub
      - slim-ai-test-orb/scan:
          name: Slim Container Scanning
          imageName: << pipeline.parameters.image-name >>
          imageConnector: << pipeline.parameters.image-connector >>
          cimgTag: << pipeline.parameters.cimg-tag >>
          requires:
            - publishLatestToHub
      